### ISSUE TITLE
Compiling not working [MAKE]

### ISSUE THREAD

**Issue by paoloronco** [aircrack-ng/rtl8812au#1131]
cd Desktop

git clone https://github.com/aircrack-ng/rtl8812au.git

cd rtl8812au

make install
install -p -m 644 88XXau.ko  /lib/modules/6.5.0-kali3-amd64/kernel/drivers/net/wireless/
install: cannot stat '88XXau.ko': No such file or directory
make: *** [Makefile:1737: install] Error 1

make install
install -p -m 644 88XXau.ko  /lib/modules/6.5.0-kali3-amd64/kernel/drivers/net/wireless/
install: cannot stat '88XXau.ko': No such file or directory
make: *** [Makefile:1737: install] Error 1

![Make not working](https://github.com/aircrack-ng/rtl8812au/assets/99389280/98d4d4fd-cd88-420f-9e60-1766279a5b33)

**Comment by MisaelK1** [comment]
Same error did u find any way to fix it?

**Comment by paoloronco** [comment]
Yes, i changed Driver and I used [those one ](https://github.com/morrownr/8812au-20210629)
Those for me works so well and no errors at all

```
mkdir -p ~/src
cd ~/src
git clone https://github.com/morrownr/8812au-20210629.git
cd ~/src/8812au-20210629
gcc –version
sudo apt install gcc-12
sudo ./install-driver.sh   

```

**Comment by ghost** [comment]
Build package dependencies per README.md

**Comment by Louay112** [comment]
The following steps fixed my issue:

1)apt update
2)apt-cache search linux-headers  # Choose the header files for Linux x.x.x-amd64 ( X depends on the version you have, so just change the X to the version that appears to you)
3)sudo apt-get install linux-headers-x.x.x-amd64  # (replace the X)
4)git clone https://github.com/aircrack-ng/rtl8812au.git # Download the driver
5)cd rtl8812au # change directory
6)sudo make && make install # install the driver
7)sudo shutdown -r 0 # reboot

Done!!!

![image](https://github.com/aircrack-ng/rtl8812au/assets/159947499/9be09da1-f7b1-4be8-8385-a094a3aea07c)

**Comment by Louay112** [comment]
sudo apt-get install linux-headers-$(uname -r)  # fixed my issue

**Comment by Louay112** [comment]
The following steps fixed my issue on Kali VM with Intel hardware:

1)sudo apt update
2)apt-cache search linux-headers  # Choose header files for Linux x.x.x-amd64 (Change X to the version that appears to you)
3)sudo apt install linux-headers-x.x.x-amd64  # (Replace X)
4)sudo shutdown -r 0 # Reboot
5)git clone https://github.com/aircrack-ng/rtl8812au.git # Download the driver
6)cd rtl8812au # Change directory
7)sudo make && make install # Install the driver
8)sudo shutdown -r 0 # Reboot

Done!!

![image](https://github.com/aircrack-ng/rtl8812au/assets/159947499/fc3a3f2d-0af8-4f23-a5eb-140ea2581db7)

**Comment by Cationator** [comment]
I followed Louay112's steps and am still having the same issue. I have tried removing and reinstalling kernel headers, tried multiple different drivers, etc. My issue seems to come down to the /lib/modules/6.6.9-amd64/build/. 


My error when using the make command:
make[1]: Entering directory '/usr/lib/modules/6.6.9-amd64/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/usr/lib/modules/6.6.9-amd64/build'


My error when using the dkms_install command
Error! Your kernel headers for kernel 6.6.9-amd64 cannot be found at /lib/modules/6.6.9-amd64/build or /lib/modules/6.6.9-amd64/source.
Please install the linux-headers-6.6.9-amd64 package or use the --kernelsourcedir option to tell DKMS where it's located.

The only thing that I notice is that the linux-headers-6.6.9-amd64 appears red when i do ls. Unsure if this is an issue.

All help greatly appreciated.

**Comment by Cationator** [comment]
Never mind, it worked minuted after I posted.

I manually removed the entire 6.6.9 directory, sudo apt remove then sudo apt install again. Reboot and verify that the correct files are in place.

I did get an error "install: cannot create regular file '/lib/modules/6.6.9-amd64/kernel/drivers/net/wireless/88XXau.ko': Permission denied" when running the make command, but my Alfa card is working just fine now so I will ignore it.

**Comment by asdfghjklrehtse** [comment]
> The following steps fixed my issue on Kali VM with Intel hardware:
> 
> 1)sudo apt update 2)apt-cache search linux-headers # Choose header files for Linux x.x.x-amd64 (Change X to the version that appears to you) 3)sudo apt install linux-headers-x.x.x-amd64 # (Replace X) 4)sudo shutdown -r 0 # Reboot 5)git clone https://github.com/aircrack-ng/rtl8812au.git # Download the driver 6)cd rtl8812au # Change directory 7)sudo make && make install # Install the driver 8)sudo shutdown -r 0 # Reboot
> 
> Done!!
> 
> ![image](https://private-user-images.githubusercontent.com/159947499/304648087-fc3a3f2d-0af8-4f23-a5eb-140ea2581db7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4ODA1MDAsIm5iZiI6MTczMzg4MDIwMCwicGF0aCI6Ii8xNTk5NDc0OTkvMzA0NjQ4MDg3LWZjM2EzZjJkLTBhZjgtNGYyMy1hNWViLTE0MGVhMjU4MWRiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQwMTIzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wM2U1M2FkNmVlZWRkNGJiZjMzMGI0ODY5YmIzMDUyMDk0Mjc3NjYyOGVkMGFjYWZhNzU5MTg3M2Q4OGUxYmE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xKnZA3wcoX_S7nHI9w-jITZOrahrOjpHqb1u5Wlyt-w)

it worked thank you

**Comment by HaMs6josef** [comment]
> The following steps fixed my issue on Kali VM with Intel hardware:
> 
> 1)sudo apt update 2)apt-cache search linux-headers # Choose header files for Linux x.x.x-amd64 (Change X to the version that appears to you) 3)sudo apt install linux-headers-x.x.x-amd64 # (Replace X) 4)sudo shutdown -r 0 # Reboot 5)git clone https://github.com/aircrack-ng/rtl8812au.git # Download the driver 6)cd rtl8812au # Change directory 7)sudo make && make install # Install the driver 8)sudo shutdown -r 0 # Reboot
> 
> Done!!
> 
> ![image](https://github.com/aircrack-ng/rtl8812au/assets/159947499/fc3a3f2d-0af8-4f23-a5eb-140ea2581db7)

Dear "Louay112"
Many thanks for your hints! For me it solve the problem!!!
(Windows10 > VMware Player17 > Kali )
