### ISSUE TITLE
NEW version v5.3.4

### ISSUE THREAD

**Issue by kimocoder** [aircrack-ng/rtl8812au#180]
We've found a new release from Edimax. It's versioned 5.3.4.

* 8814au 5ghz got issues, while for 8812/8821 it's working.
* 8814au VHT got issues, report in below comment
* Cannot set channel with iw/netlink (v5.1.5 and v5.2.20 works)
* txpower control doesn't seem to work anymore (worked with v5.2.20(.2))
* the get channel function got a compile error related to "CHANNEL_WIDTH_5" and "CHANNEL_WIDTH_10" this was working properly in v5.1.5 again.

Couple of things to work with :+1:

**Comment by kimocoder** [comment]
@fariouche I see some interesting things in the code.. I think they have used some code found around + added own stuff on top on that again. The driver actually support injection allready, I bet I know where that came from ;)

The driver looks promising on several places. Got more time to look at it soon.

**Comment by fariouche** [comment]
cool. Agree with you, same feeling, better base here.
Do not forget that until now, we used various patches coming all from various older versions of realtek. So it's not surprising me that we found them all here.
I see that the main new feature is mesh, don't know what use will be for us.

I will need to add the multi chip support again I think

**Comment by kimocoder** [comment]
Yes, step 1 should be to get all 3 chipset working, from there I have to do a walkthrough on whats added and not, as there is no changelog or commit log available.

**Comment by fariouche** [comment]
@kimocoder , I've pushed you my 5.3.4 branch, with the 8814 support in it :-)
It still needs some work. In AP mode I'm missing RX_STBC1 option... I doubt that the VHT mode is enabled for the 8814 at least.
I see also a kernel oops when rmmod the driver sometimes, to be investigated.

Injection may not work..

But globaly it works. I've not tested the 8821 or the 8811 yet. But this should be a good base for you to continue until I return mid-september

**Comment by kimocoder** [comment]
I see it, there are conflicts to the PR, anyway I got lots to do with it besides the chip support. :)

Aaah I see the conflicts.. you added the v5.3.4 on top of v5.2.20.2, but what I did is cleaned out the v5.2.20.2 and forked a "clean" v5.3.4.. how should we do this?

I may of course clean it out and put your solution in, should I do it?
cause there are 2 ways and we did go seperate ways on it, but if your way (putting v5.3.4 on top v5.2.20.2) works and doesn't give any big headaches (major errors) I'll add it that way instead.

**Comment by kimocoder** [comment]
I'll go ahead and try it see how it actually works out. Just leave the PR open I'll grab it after dinner. Thanks!

[Update] Actually, injection is working for the 8814au. But getting lots of kernel oops too.
Another thing I notice.. injection here is much faster, especially on 8812/8811 (8821). Also, seems like the performance (power) of this driver is WAY better than branches below we've done.. which is.. just GREAT

**Comment by fariouche** [comment]
the oops seems to be linked to this function:
_rtw_hal_macid_bmp_sleep

I'm not sure why, but they changed the function code. Maybe a pointer setting is missing in the 8814 specific part. Should not be too hard to fix

**Comment by kimocoder** [comment]
This build is actually ported from the master (Larry Finger aka lwfinger) at https://github.com/lwfinger I've found. That's also great need, cause his the best at Realtek there is. Great news, I started working on unreachable switches and compile errors. Hard to see whats done and not.. since there is no commit log, I have to do a major walkthrough

**Comment by fariouche** [comment]
I checked the lwfinger repo, lot of drivers, but they seem all very old code base.

Indeed, I see also many compilation warnings that may hide real bugs...

FYI, I just fixed the bug for the 8814. not more warnings/oops
I've put values in the hal that I believe correct, but not 100% sure

**Comment by fariouche** [comment]
this will be my last commit. I will keep reading my email from time to time

**Comment by kimocoder** [comment]
Just pushed the changes manually. Fixed USB3 with the modeswitch and compilation warnings. Had to throw in you 8814 kernel oops fix by hand, cause your repo can't merge with both mine or aircrack-ng, so when you get back from holiday, delete your fork and re-fork it (from the aircrack-ng repo) again to get it to work. Have a GREAT holiday sir! :1st_place_medal: :+1:

**Comment by kimocoder** [comment]
Merged a commit with support for kernel v4.19-rc1 (thanks to a commit made over at "gordboy" and "paspro")

Notes to the v5.3.4..
VHT and everything (injection too) seems to be working at this point.. but there are few notes to work with.. @kcdtv also report that wpa_supplicant and iw scans are actually working with this new base, that's also great news. It seems dandy and more stable.

However.. this is more like a "note-to-self" but sharing is caring isn't it?

* 8814au 5ghz got issues, while for 8812/8821 it's working.
* 8814au VHT got issues, report in below comment
* Cannot set channel with iw/netlink (v5.1.5 and v5.2.20 works)
* txpower control doesn't seem to work anymore (worked with v5.2.20(.2))
* the get channel function got a compile error related to "CHANNEL_WIDTH_5" and "CHANNEL_WIDTH_10" this was working properly in v5.1.5 again.

Couple of things to work with :+1:

**Comment by ggerla** [comment]
I try to use this driver with a rtl8814au device, but i'm not able to use VHT functionality.
With hostapd the channel bandwidth is always 40MHz and maximum speed is 150Mb/s.

**Comment by kimocoder** [comment]
Yup, thanks for the heads up. Using the above comment as a TODO. putting it in there

**Comment by fariouche** [comment]
"txpower control doesn't seem to work anymore (worked with v5.2.20(.2))"
-> I do remember having seen something about it in the code, and I didn't include them. Should be easy to fix

**Comment by kimocoder** [comment]
Yes the working commit for the v5.2.20 branch is here https://github.com/aircrack-ng/rtl8812au/commit/f6461d311d5732a340b1381899818f4729b553f6

I'm moving and starting on a new job shortly and got to spend some time getting in place over there, but will be back soon again.

**Comment by fariouche** [comment]
the txpower commit is already in the 5.3.4...
Is the twpower control not working for all chipsets? or only the 8814 has the issue?

**Comment by kimocoder** [comment]
I think it's all, not sure at all but

**Comment by kimocoder** [comment]
@aircrack-ng @Mister_X may you change "standard branch" om settings, instead of "v5.1.5" branch, the "v5.2.20" may be set instead

**Comment by francoism90** [comment]
@kimocoder Is it correct you used EW-7811UAC for the source? :)

Just some debug info from an ASUS AC68U USB on branch v5.3.4:
```
$ iwconfig
wlp0s20f0u4  IEEE 802.11AC  ESSID:"***"  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency:5.22 GHz  Access Point: ***
          Bit Rate:1.3 Gb/s   Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality=100/100  Signal level=52/100  Noise level=0/100
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

$ iw wlan0 info
Interface wlan0
        ifindex 14
        wdev 0x300000001
        addr ***
        ssid ***
        type managed
        wiphy 3
        channel 44 (5220 MHz), width: 80 MHz, center1: 5250 MHz
        txpower 18.00 dBm

$ iw list                                                             
Wiphy phy3
        max # scan SSIDs: 9
        max scan IEs length: 2304 bytes
        max # sched scan SSIDs: 0
        max # match sets: 0
        max # scan plans: 1
        max scan plan interval: -1
        max scan plan iterations: 0
        Retry short limit: 7
        Retry long limit: 4
        Coverage class: 0 (up to 0m)
        Supported Ciphers:
                * WEP40 (00-0f-ac:1)
                * WEP104 (00-0f-ac:5)
                * TKIP (00-0f-ac:2)
                * CCMP-128 (00-0f-ac:4)
        Available Antennas: TX 0 RX 0
        Supported interface modes:
                 * IBSS
                 * managed
                 * AP
                 * monitor
                 * P2P-client
                 * P2P-GO
        Band 1:
                Capabilities: 0x1b73
                        RX LDPC
                        HT20/HT40
                        Static SM Power Save
                        RX Greenfield
                        RX HT20 SGI
                        RX HT40 SGI
                        RX STBC 3-streams
                        Max AMSDU length: 7935 bytes
                        DSSS/CCK HT40
                Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
                Minimum RX AMPDU time spacing: 16 usec (0x07)
                HT Max RX data rate: 450 Mbps
                HT TX/RX MCS rate indexes supported: 0-23
                Bitrates (non-HT):
                        * 1.0 Mbps
                        * 2.0 Mbps
                        * 5.5 Mbps
                        * 11.0 Mbps
                        * 6.0 Mbps
                        * 9.0 Mbps
                        * 12.0 Mbps
                        * 18.0 Mbps
                        * 24.0 Mbps
                        * 36.0 Mbps
                        * 48.0 Mbps
                        * 54.0 Mbps
                Frequencies:
                        * 2412 MHz [1] (20.0 dBm)
                        * 2417 MHz [2] (20.0 dBm)
                        * 2422 MHz [3] (20.0 dBm)
                        * 2427 MHz [4] (20.0 dBm)
                        * 2432 MHz [5] (20.0 dBm)
                        * 2437 MHz [6] (20.0 dBm)
                        * 2442 MHz [7] (20.0 dBm)
                        * 2447 MHz [8] (20.0 dBm)
                        * 2452 MHz [9] (20.0 dBm)
                        * 2457 MHz [10] (20.0 dBm)
                        * 2462 MHz [11] (20.0 dBm)
                        * 2467 MHz [12] (20.0 dBm)
                        * 2472 MHz [13] (20.0 dBm)
                        * 2484 MHz [14] (20.0 dBm) (no IR)
        Band 2:
                Capabilities: 0x1b73
                        RX LDPC
                        HT20/HT40
                        Static SM Power Save
                        RX Greenfield
                        RX HT20 SGI
                        RX HT40 SGI
                        RX STBC 3-streams
                        Max AMSDU length: 7935 bytes
                        DSSS/CCK HT40
                Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
                Minimum RX AMPDU time spacing: 16 usec (0x07)
                HT Max RX data rate: 450 Mbps
                HT TX/RX MCS rate indexes supported: 0-23
                VHT Capabilities (0x03c054b2):
                        Max MPDU length: 11454
                        Supported Channel Width: neither 160 nor 80+80
                        RX LDPC
                        short GI (80 MHz)
                        TX STBC
                        SU Beamformee
                        +HTC-VHT
                VHT RX MCS set:
                        1 streams: MCS 0-9
                        2 streams: MCS 0-9
                        3 streams: MCS 0-9
                        4 streams: not supported
                        5 streams: not supported
                        6 streams: not supported
                        7 streams: not supported
                        8 streams: not supported
                VHT RX highest supported: 1300 Mbps
                VHT TX MCS set:
                        1 streams: MCS 0-9
                        2 streams: MCS 0-9
                        3 streams: MCS 0-9
                        4 streams: not supported
                        5 streams: not supported
                        6 streams: not supported
                        7 streams: not supported
                        8 streams: not supported
                VHT TX highest supported: 1300 Mbps
                Bitrates (non-HT):
                        * 6.0 Mbps
                        * 9.0 Mbps
                        * 12.0 Mbps
                        * 18.0 Mbps
                        * 24.0 Mbps
                        * 36.0 Mbps
                        * 48.0 Mbps
                        * 54.0 Mbps
                Frequencies:
                        * 5180 MHz [36] (20.0 dBm)
                        * 5200 MHz [40] (20.0 dBm)
                        * 5220 MHz [44] (20.0 dBm)
                        * 5240 MHz [48] (20.0 dBm)
                        * 5260 MHz [52] (20.0 dBm) (no IR, radar detection)
                        * 5280 MHz [56] (20.0 dBm) (no IR, radar detection)
                        * 5300 MHz [60] (20.0 dBm) (no IR, radar detection)
                        * 5320 MHz [64] (20.0 dBm) (no IR, radar detection)
                        * 5500 MHz [100] (20.0 dBm) (no IR, radar detection)
                        * 5520 MHz [104] (20.0 dBm) (no IR, radar detection)
                        * 5540 MHz [108] (20.0 dBm) (no IR, radar detection)
                        * 5560 MHz [112] (20.0 dBm) (no IR, radar detection)
                        * 5580 MHz [116] (20.0 dBm) (no IR, radar detection)
                        * 5600 MHz [120] (20.0 dBm) (no IR, radar detection)
                        * 5620 MHz [124] (20.0 dBm) (no IR, radar detection)
                        * 5640 MHz [128] (20.0 dBm) (no IR, radar detection)
                        * 5660 MHz [132] (20.0 dBm) (no IR, radar detection)
                        * 5680 MHz [136] (20.0 dBm) (no IR, radar detection)
                        * 5700 MHz [140] (20.0 dBm) (no IR, radar detection)
                        * 5720 MHz [144] (20.0 dBm) (no IR, radar detection)
                        * 5745 MHz [149] (20.0 dBm) (no IR)
                        * 5765 MHz [153] (20.0 dBm) (no IR)
                        * 5785 MHz [157] (20.0 dBm) (no IR)
                        * 5805 MHz [161] (20.0 dBm) (no IR)
                        * 5825 MHz [165] (20.0 dBm) (no IR)
                        * 5845 MHz [169] (disabled)
                        * 5865 MHz [173] (disabled)
                        * 5885 MHz [177] (disabled)
        Supported commands:
                 * new_interface
                 * set_interface
                 * new_key
                 * start_ap
                 * new_station
                 * set_bss
                 * join_ibss
                 * set_pmksa
                 * del_pmksa
                 * flush_pmksa
                 * remain_on_channel
                 * frame
                 * set_channel
                 * connect
                 * disconnect
        Supported TX frame types:
                 * IBSS: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * managed: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * AP: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * AP/VLAN: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * P2P-client: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * P2P-GO: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
        Supported RX frame types:
                 * IBSS: 0xd0
                 * managed: 0x40 0xd0
                 * AP: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
                 * AP/VLAN: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
                 * P2P-client: 0x40 0xd0
                 * P2P-GO: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
        WoWLAN support:
                 * wake up on anything (device continues operating normally)
        software interface modes (can always be added):
                 * monitor
        interface combinations are not supported
        Device supports scan flush.
```
The Signal level is lower for some reason on the v5.*.* branches, don't know why.
When using v4.*.* it is usually between 80-100. It also loses connection sometimes, but I'm also having this issue on v4.*.* - it must be something else causing this.

EDIT: weird, it seems disabling `docker.service` fixes the disconnect and slow performance issues. Maybe something goes wrong on multiple connections/adapters.

I'm impress by the overall performance of this driver, it seems to be stable and reaching the reported ISP speed.

**Comment by kimocoder** [comment]
Correct, Edimax sources on the v5.3.4 with all patches from v5.2.20(.2) on top of it

**Comment by francoism90** [comment]
@kimocoder Great work! I'm happy to test and debug if needed. :)

**Comment by fariouche** [comment]
For info, I'm currently working with the 8814 to improve speed inAP mode.
I'm currently stuck at 300mbps, even if the iw list displays 1300mbps max.
My phone can go up to 866Mbps.

@kimocoder, IAsked realtek for source code, no answer yet. I think that realtek will share a driver as is to alpha if they request it. if we can get a hand on the 5.3.4 with 8814, it will help a lot.

**Comment by kimocoder** [comment]
Ok. I'm still a bit busy with moving, but will be back online again soon.

**Comment by francoism90** [comment]
@fariouche Same here, it says 1300mbps, also reaching a max. speed of around 300mbps.
Glad you're looking into tweaking it. :)

In the past I've also contacted Realtek for the source code of the 8814au.. haven't received any response in months, so don't expect a reply. :/

**Comment by fariouche** [comment]
no problems, it is not urgent.

**Comment by francoism90** [comment]
I'm unable to set monitor mode, is this a known bug? It results in a module error.
To restore I need to unload and reload the 88xx module.
Please let me know if you need any debug info. :)

Edit, some router (merlin) debug info that may be the issue with the speed:

It seems to be hitting a low speed quite a lot (Rx/**Tx** & RSSI):
```
780 / **6 Mbps**
-52 dBm
```

Instead of around:
```
780 / 878 Mbps
-52 dBm
```

**Comment by fariouche** [comment]
Nerver tested the monitor mode.
Can you tell me the commands you used to enter monitor mode?
Can you also post the dmesg output if it crashed ?(if any)

For the tx power of the 8814, I'm still looking at it, but maybe a bug in the power management. I'll test a fix in a few hours

**Comment by fariouche** [comment]
About the speed of the 8814, seeing the following table (https://d2cpnw0u24fjm4.cloudfront.net/wp-content/uploads/80211-Data-rates-and-snr-requriements-screen-shot.png) It seems that MCS8 and MCS9 are not selected.
300Mbps means Short GI-40MHz VHT MCS7 2SS. My phone is 2 SS so it is expected, but I do not understand why it didn't select MCS9...
For the 80MHz bandwidth, I still need to check if my hostapd.conf file is using a compatible channel (I doubt that) so it may explain that I do not have 80Mhz.

**Comment by fariouche** [comment]
For information about 8814:

- [ ] 8814au 5ghz got issues, while for 8812/8821 it's working. --> I cannot reproduce the issue
- [x] 8814au VHT got issues, report in below comment --> VHT is working, but limited, see below
- [ ] Cannot set channel with iw/netlink (v5.1.5 and v5.2.20 works)
- [x] txpower control doesn't seem to work anymore (worked with v5.2.20(.2)) --> indeed, iw is not even calling the set_tx_power... I have to dig inside iw to understand the condition.
- [ ] the get channel function got a compile error related to "CHANNEL_WIDTH_5" and "CHANNEL_WIDTH_10" this was working properly in v5.1.5 again.
- [x] Cannot negociate above 300Mbps when in AP mode. I have the exact same issue with the 8812 and 8814 so this is not related to the 8814 code... The code should work, so maybe a hostapd issue? Still investigating...
- [x] No LEDs with 8814. Not sure why, all the functions are here and doing the same as before... I will try with an older driver to see if the led is working


Lot of work to unleash the full potential of theses chips

**Comment by francoism90** [comment]
@fariouche Thanks for looking into the issues and trying to solve them. Such a shame Realtek isn't able to produce a good working driver. :/

I can confirm it seems to be capt at 300Mbps max. (5Ghz, 802.11ac, ASUS AC-78U), the same issue (with same device + PC) happens on Windows 10 though, so maybe something is happening with the Realtek-device itself?
LED indeed doesn't work, but I'm happy because the one on the AC-68U-USB simple blinds you. ;)

Thanks again and if debug/testing is needed, please let me know. :)

**Comment by fariouche** [comment]
May have found the reason why VHT is not enabled (for all chipsets!)
Got a patch, that needs testing, but I got my phone to negociate the link at 780Mbps. (this means 80Mhz MCS8, almost the max of my phone. MCS9 is maybe not selected because of too many wifi around)

THe problem is a bad condition with MESH mode... why? I do not know.
Eitther the condition is wrong (and commenting the condition makes it work) or the MESH mode is wrongly reported.
I had the feeling that the mesh mode is not yet fully supported by this driver (because it actually appeared with this driver!)

Keep you in touch as soon as I've make a deeper look and more tests about the actual speed

**Comment by fariouche** [comment]
Until kimocoder got time to commit the VHT fix here, I've looked at the tx power issue.
iwconfig is not supported. The ioctl is not even coded in the driver. So forget it (iwconfig is deprecated anyway)
Using iw, you have to be careful. The tx power unit is milli-Bel-milliwatt.

Some info on the internet shows the wrong command, that may work for kernel < 2.6.36 or with the option COMPAT_KERNEL_RELEASE.

I got it tx power working using the following command line:
sudo iw dev wlan0 set txpower fixed 1100

and not 11mBm as shown in some pages. So, do not forget to multiply the value by 100.

After that, iw dev wlan0 info display the correct txpower.

Now, I have no way to verify that the txpower is actually applied. The driver will store the value in a variable, call a lower level function to actually set the tx power and... well no errors, but not sure either.
Calling the get txpower ioctl will just return the value stored previously. Seems to be no way to actually probe the firmware for the actual really applied value....

If someone is able to verify, it will be great

**Comment by kimocoder** [comment]
Ok. I've merged the VHT fix. iwconfig is deprecated too, so iw should be used in the future.
I'm back on ny computer again in 4 days now, finally

**Comment by francoism90** [comment]
@kimocoder Thanks for the merge! Do you need debug info?
So far downloading seems to be working fine ~28.8MB/s pretty stable. :)

@fariouche are you sure? I'm able to set the tx-power just fine:
```
phy#0
        Interface wlp0s20f0u4
                ifindex 2
                wdev 0x1
                addr ..
                ssid ...
                type managed
                channel 44 (5220 MHz), width: 80 MHz, center1: 5250 MHz
                txpower 30.00 dBm
```

I'm using the following systemd service:
```
# /etc/systemd/system/88XXau@.service
[Unit]
Description=Set TX-Power and Monitor-mode %I
After=systemd-udevd.service network-pre.target systemd-sysctl.service
Before=network.target multi-user.target shutdown.target
Wants=network.target

[Service]
Type=oneshot
RemainAfterExit=yes
#ExecStart=sh -c 'ip link set %i down; iw dev %i set type monitor; ip link set %i up; iw %i set txpower fixed 3000'
ExecStart=sh -c 'iw %i set txpower fixed 3000'

[Install]
WantedBy=multi-user.target
```

**Comment by fariouche** [comment]
@francoism90 , yes, your systemd script is indeed correct (using iw with txpower value multiplied by 100). What is not working is calling iw set txpower with '30mBm' literally...

28.8Mbits is good. Using my phone I went as high as 400Mbits (samsung S7 edge)

**Comment by fariouche** [comment]
testing the wifi at 866Mbps I can reach the maximum real bandwith (270Mbps). Really good.
Also fixed the led blinking.
This can be disabled by commenting the CONFIG_RTW_LED define in autoconf.h

**Comment by francoism90** [comment]
@kimocoder @fariouche I'm really impressed! Finally I'm able to browse and download without issues. :)
Will try to test the LED.

**Comment by fariouche** [comment]
I'm essentially using it as an AP, so glad it works good in station mode.
I believe that v5.3.4 is the best driver we have so far. Still need some corner fixes.
Monitor and injection mode need to be confirmed yet.

**Comment by francoism90** [comment]
Just some build errors on latest commit:
```
DKMS make.log for rtl8812au-5.3.4 for kernel 4.18.12-1-ck-skylake (x86_64)
ma  8 okt 2018 15:58:53 CEST
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.18.12-1-ck-skylake/build M=/var/lib/dkms/rtl8812au/5.3.4/build  modules
make[1]: Entering directory '/usr/lib/modules/4.18.12-1-ck-skylake/build'
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_cmd.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_security.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_debug.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_io.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_ioctl_query.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_ioctl_set.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_ieee80211.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_mlme.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_mlme_ext.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_mi.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_wlan_util.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_vht.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_pwrctrl.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_rf.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_recv.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_sta_mgt.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_ap.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/mesh/rtw_mesh.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/mesh/rtw_mesh_pathtbl.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/mesh/rtw_mesh_hwmp.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_xmit.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_p2p.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_rson.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_tdls.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_br_ext.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_iol.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_sreset.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_btcoex_wifionly.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_btcoex.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_beamforming.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_odm.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_rm.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/rtw_rm_fsm.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/core/efuse/rtw_efuse.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/os_dep/osdep_service.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/os_dep/linux/os_intfs.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/os_dep/linux/usb_intf.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/os_dep/linux/usb_ops_linux.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/os_dep/linux/ioctl_linux.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/os_dep/linux/xmit_linux.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/os_dep/linux/mlme_linux.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/os_dep/linux/recv_linux.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/os_dep/linux/ioctl_cfg80211.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/os_dep/linux/rtw_cfgvendor.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/os_dep/linux/wifi_regd.o
/var/lib/dkms/rtl8812au/5.3.4/build/os_dep/linux/ioctl_cfg80211.c: In function ‘cfg80211_rtw_get_channel’:
/var/lib/dkms/rtl8812au/5.3.4/build/os_dep/linux/ioctl_cfg80211.c:5563:5: warning: enumeration value ‘CHANNEL_WIDTH_5’ not handled in switch [-Wswitch]
     switch(pHalData->current_channel_bw){
     ^~~~~~
/var/lib/dkms/rtl8812au/5.3.4/build/os_dep/linux/ioctl_cfg80211.c:5563:5: warning: enumeration value ‘CHANNEL_WIDTH_10’ not handled in switch [-Wswitch]
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/os_dep/linux/rtw_android.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/os_dep/linux/rtw_proc.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/os_dep/linux/rtw_rhashtable.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/os_dep/linux/ioctl_mp.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/hal/hal_intf.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/hal/hal_com.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/hal/hal_com_phycfg.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/hal/hal_phy.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/hal/hal_dm.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/hal/hal_dm_acs.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/hal/hal_btcoex_wifionly.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/hal/hal_btcoex.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/hal/hal_mp.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/hal/hal_mcc.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/hal/hal_hci/hal_usb.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/hal/led/hal_led.o
  CC [M]  /var/lib/dkms/rtl8812au/5.3.4/build/hal/led/hal_usb_led.o
In file included from /var/lib/dkms/rtl8812au/5.3.4/build/hal/hal_mp.c:17:
/var/lib/dkms/rtl8812au/5.3.4/build/hal/hal_mp.c: In function ‘mpt_ProSetPMacTx’:
/var/lib/dkms/rtl8812au/5.3.4/build/hal/hal_mp.c:2091:31: error: ‘padapter’ undeclared (first use in this function); did you mean ‘_adapter’?
    if (IS_HARDWARE_TYPE_8814A(padapter))
                               ^~~~~~~~
/var/lib/dkms/rtl8812au/5.3.4/build/include/drv_types.h:1616:46: note: in definition of macro ‘rtw_get_hw_type’
 #define rtw_get_hw_type(adapter) (((PADAPTER)adapter)->dvobj->HardwareType)
                                              ^~~~~~~
/var/lib/dkms/rtl8812au/5.3.4/build/include/hal_intf.h:530:3: note: in expansion of macro ‘IS_HARDWARE_TYPE_8814AE’
  (IS_HARDWARE_TYPE_8814AE(_Adapter) || IS_HARDWARE_TYPE_8814AU(_Adapter) || IS_HARDWARE_TYPE_8814AS(_Adapter))
   ^~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/rtl8812au/5.3.4/build/hal/hal_mp.c:2091:8: note: in expansion of macro ‘IS_HARDWARE_TYPE_8814A’
    if (IS_HARDWARE_TYPE_8814A(padapter))
        ^~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/rtl8812au/5.3.4/build/hal/hal_mp.c:2091:31: note: each undeclared identifier is reported only once for each function it appears in
    if (IS_HARDWARE_TYPE_8814A(padapter))
                               ^~~~~~~~
/var/lib/dkms/rtl8812au/5.3.4/build/include/drv_types.h:1616:46: note: in definition of macro ‘rtw_get_hw_type’
 #define rtw_get_hw_type(adapter) (((PADAPTER)adapter)->dvobj->HardwareType)
                                              ^~~~~~~
/var/lib/dkms/rtl8812au/5.3.4/build/include/hal_intf.h:530:3: note: in expansion of macro ‘IS_HARDWARE_TYPE_8814AE’
  (IS_HARDWARE_TYPE_8814AE(_Adapter) || IS_HARDWARE_TYPE_8814AU(_Adapter) || IS_HARDWARE_TYPE_8814AS(_Adapter))
   ^~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/rtl8812au/5.3.4/build/hal/hal_mp.c:2091:8: note: in expansion of macro ‘IS_HARDWARE_TYPE_8814A’
    if (IS_HARDWARE_TYPE_8814A(padapter))
        ^~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:317: /var/lib/dkms/rtl8812au/5.3.4/build/hal/hal_mp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/var/lib/dkms/rtl8812au/5.3.4/build/hal/hal_hci/hal_usb.c: In function ‘usb_init_recv_priv’:
/var/lib/dkms/rtl8812au/5.3.4/build/hal/hal_hci/hal_usb.c:28:8: warning: cast between incompatible function types from ‘void (*)(void *)’ to ‘void (*)(long unsigned int)’ [-Wcast-function-type]
        (void(*)(unsigned long))usb_recv_tasklet,
        ^
make[1]: *** [Makefile:1521: _module_/var/lib/dkms/rtl8812au/5.3.4/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.18.12-1-ck-skylake/build'
make: *** [Makefile:2054: modules] Error 2
```

**Comment by fariouche** [comment]
oops, I was sure to have tested... sorry. Fixed. Should be available shortly

**Comment by fariouche** [comment]
Status information about 8814:

* [x]  8814au 5ghz got issues, while for 8812/8821 it's working. --> I cannot reproduce the issue
* [x]  8814au VHT got issues, report in below comment --> VHT is working, but limited, see below
* [ ]  Cannot set channel with iw/netlink (v5.1.5 and v5.2.20 works)
* [x]  txpower control doesn't seem to work anymore (worked with v5.2.20(.2)) --> indeed, iw is not even calling the set_tx_power... I have to dig inside iw to understand the condition.
* [ ]  the get channel function got a compile error related to "CHANNEL_WIDTH_5" and "CHANNEL_WIDTH_10" this was working properly in v5.1.5 again.
* [x]  Cannot negociate above 300Mbps when in AP mode. I have the exact same issue with the 8812 and 8814 so this is not related to the 8814 code... The code should work, so maybe a hostapd issue? Still investigating...
* [x]  No LEDs with 8814. Not sure why, all the functions are here and doing the same as before... I will try with an older driver to see if the led is working
* [x] Fixed 8811 and 8821 support

**Comment by francoism90** [comment]
@fariouche How can I disable the LED? :)
I have changed the `include/autoconf.h` line to `/*#define CONFIG_RTW_LED*/`, but this results in build errors.

**Comment by fariouche** [comment]
indeed, it does not compile. Will fix it asap

**Comment by fariouche** [comment]
By the way, after looking at the code (current and old ones, like 4.3.21) I do not see how the set_txpower can work.
The ioctl only set a variable, and return it when the get_txpower is return. But internally it is totally ignored.
So a really doubt that the txpower is actually working at all. It's all fake.!

**Comment by fariouche** [comment]
@francoism90 , you will be able to disable leds by commenting CONFIG_RTW_SW_LED as soon as the fix is pushed here

**Comment by kimocoder** [comment]
Pushed. Awesome, you really did some magic over there @fariouche

**Comment by fariouche** [comment]
thanks ;-) . Still not happy myself. I would like to push the tx power... But one comment in the code by realtek makes me fear to destroy the dongle. (something about limiting to some kind of magic value that they got by experimenting because they don't want to fry the power module...)

**Comment by kimocoder** [comment]
Remember my dear frenchie, you could always do it, suggested adapter would be the 8811 chipset.

You know our favorite manufacturer would sacrifice some hardware to fix the most important issues of them all, the one and beloved txpower (range/distance) I'm pretty sure it's allright, just be sure to probe through the code before frying 'em all 😅

**Comment by francoism90** [comment]
@fariouche Hmm, I'm still getting build errors with `CONFIG_RTW_SW_LED` commented in `include/autoconf.h`. Are you sure this is the correct line? :)

**Comment by fariouche** [comment]
Yes I'm sure. But I just check the code here and it is not correct. My repo and kimo's one is correct... so something wasn't pushed here completely. @kimocoder ?

**Comment by kimocoder** [comment]
I actually forgot to pull it. Try again, I just did so

**Comment by francoism90** [comment]
@fariouche @kimocoder Many thanks, working now! :)
I'm sorry to bother you guys over this minor issue. ASUS has decided to use a very bright LED and I have this adapter on my desk.

Keep up the good work. :+1:

**Comment by kimocoder** [comment]
No problem, we're happy to resolve the issue.
@fariouche I got a good idea.. found a Realtek driver that actually works like a charm, and that's the rtl8187 driver.. starting inspection of it, 'cause ut doesn't have the issues we're struggling with and the range (txpower) is AMAZING on it.

**Comment by fariouche** [comment]
I'm currently fighting with the tx power... I've read all the code, and implemented a fix, but not sure about testing. If I set the 8811 as an AP using hostapd, change the txpower, I'm expecting to have a big impact on the range... I can see a difference, but not very sure.

Where is that rtl8187 driver? github?

**Comment by kimocoder** [comment]
Information regarding rtl8187 is [herr](https://www.aircrack-ng.org/doku.php?id=r8187)

Do you need a USB ammeter for proper testing? I got the ultimate USB ammeters with bluetooth support and APP for it. I'll ship you one!

rtl8187 (r8187) has different versions, both ieee80211 and a mac80211 (which I think is included upstream debian maibtained by Johannes Berg) *my thought without confirmation* er have a ieee80211 driver here, som why not start there. Anyways, the Kali version or it kicks ass, my old Alfa adapter with the chipset is really SUPERIOR what matters range and penetration testing usages (mon/inject support) working flawless

**Comment by fariouche** [comment]
found some code in github... it is rather old (5years).
This chip seems different too. Everything is managed by the driver, with power tables etc.
What makes things difficult with the 8812/21 etc is that the tx power is managed by the firmware, and we do not have access to the tables.

The driver can only write a tx power index in a register, and the firmware will decide what to do with it. What is the corresponding dBm value? impossible to say (and seeing some realtek comments, they don't too...). This is just a matter of calibrating the values. WIth a spectrum analyzer, it may be possible to get real dBm values.

To make things even worse, some dongles are flashed with a country code that cannot be changed. They do not allow any tx power enforcement :-( 

As far as I understood the driver's logic, at some point, settcpower is called.
The function is then getting the proper tx power index depending on various tables (loaded from the eeprom) and current link settings (bandwith, rate, channel etc)
So, theorically, we should be able to fix the tx power by alway returning a fixed tx power index.

I do not have an usb ampmeter, this is indeed a good idea.
I've looked at the ieee80211 version of the driver, found on github.

I can have access to a spectrum analyzer at work, but the access it limited, so I'm authorized only when not in use and only for 15min. I must be sure and quick lol.

**Comment by kimocoder** [comment]
Ok. Interesting reading! Still not got my computer by hand, but hopefully try going getting ny hands on it this weekend again :+1: A USB ammater is on it's way!

**Comment by kimocoder** [comment]
Just pushed various fixes / cleanups.

* Remove TESTCHIP support
* Nuke rtw_proc aka debug via /proc
* Minor fix on the inconsistent teardown (from upstream)
* Hard disable old debug read/write file functions
* Remove unneeded read firmware support
* Remove unneeded objs from Makefile 
* Remove more objs from unsupported chips
* Makefile cleanup
* Remove unused firmware load
* Support kernel PIC mode for compiling

**Comment by francoism90** [comment]
@kimocoder Going to test and let you know, thanks for your hard work!
Does this also mean this fixes the TX-power issues?

**Comment by kimocoder** [comment]
No it removes some firmware load mostly, besides that it looks more cleaner and easier for devs to probe through

**Comment by kimocoder** [comment]
Got my computer from my other apartment this weekend, finally after 3 weeks off my computers grid, feels really good. Had a productive weekend studying the tip @aircrack-ng gave me. the rtl8822bu repo (driver) from [ulli-kroll](https://github.com/ulli-kroll/rtl8822bu), not that I didn't follow him from before (cause the 8814AU HAL files originated from him before it got added the injection capabilities (from the start off) and added to the rtl8812au driver by [astsam)](https://github.com/astsam/rtl8812au) but he's been active again lately after some time off (propably got a life himself) and I didn't notice.
*sidetracked* BUT, probing through ulli-krolls repos and diving into the code from many drivers found there just confirms my thought all the long.. the BASE (Realtek) code is the same in most drivers, but each drivers has different patches/fixes/cleanups/you name it added to it, so the fixes above is a collection of some of them. It's is kinda "good" news, 'cause it's possibly to pull patches/fixes from them, but if I could tag Realtek here.. I'd do it!

Anyways, ontrack the rtl8822bu repo got some fixes and the one I didn't include from it was the
PHY_PARA_FILE function which should be removed. [here](https://github.com/ulli-kroll/rtl8822bu/commit/8b9274c2c98d630a035673a36044686b67ab698b) it should also remove minor firmware load.
Adding it for later.

@fariouche the UM43C USB3.0 bluetooth ammeter is shipped.

![img_20181021_231952](https://user-images.githubusercontent.com/4252297/47272588-26525a80-d588-11e8-9e44-3bbd6201aece.jpg)

**Comment by Yes21** [comment]
Does 5.3.4 compiles on RPI ?

I can't see CONFIG_PLATFORM_ARM_RPI in the 
makefile ...

**Comment by fariouche** [comment]
should be.
This flag does not make sense at the first place, this is a normal linux after all

**Comment by Yes21** [comment]
So do I only need to add `CONFIG_PLATFORM_ARM_RPI=y` in the Makefile, to be able to compile on RPI ?

**Comment by kimocoder** [comment]
I may take a look at it this evening

**Comment by ghost** [comment]
If I need the rtl8821au, how can I build the one in 5.3.4?
Do I have to change the makefile in CONFIG_BT_COEXIST = y?
Because the 8821au chips come together with BT.

**Comment by fariouche** [comment]
never tested this flag. But this feature is just an HW optimization to tel the BT HW to avoid some frequencies.
Your wifi should work out of the box. If you want to try the flag after, please do so. (it may not build)

**Comment by ghost** [comment]
> never tested this flag. But this feature is just an HW optimization to tel the BT HW to avoid some frequencies.
> Your wifi should work out of the box. If you want to try the flag after, please do so. (it may not build)

Thank you! now i see in wikidevi.com that only one drive use 8821au . i will let it out from my tests.
Cheers

**Comment by ghost** [comment]
ok, i understand now that's this one working for three(8812,8821,8814) it's good:
**i have changes in Makefile the**

ifeq ($(CONFIG_RTL8812A)_$(CONFIG_RTL8821A)_$(CONFIG_RTL8814A), y_y_y)

EXTRA_CFLAGS += -DDRV_NAME=\"rtl88**xx**au\"
ifeq ($(CONFIG_USB_HCI), y)
USER_MODULE_NAME = **rtl**88**xx**au
endif
ifeq ($(CONFIG_PCI_HCI), y)
USER_MODULE_NAME = **rtl**88**xx**ae
endif
ifeq ($(CONFIG_SDIO_HCI), y)
USER_MODULE_NAME = **rtl**88**xx**as
endif
...
ifeq ($(CONFIG_PLATFORM_I386_PC), y)
...
MODDESTDIR := /lib/modules/$(KVER)/kernel/3rdparty/rtl88xxau    ##for testing keep kernel/drivers...clean

########

**and become a clean dkms**

apt-get install dkms-rtl88xxau-5.3.4-3pclos2018*.rpm
Reading Package Lists... Done
Building Dependency Tree... Done
Selecting dkms-rtl88xxau for 'dkms-rtl88xxau-5.3.4-3pclos2018.x86_64.rpm'
The following NEW packages will be installed:
   dkms-rtl88xxau (5.3.4-3pclos2018)
0 upgraded, 1 newly installed, 0 removed and 0 not upgraded.
Need to get 0B/14.9MB of archives.
After unpacking 30.1MB of additional disk space will be used.
Committing changes...
Preparing                                ############################## [100%]
Updating / installing
  dkms-rtl88xxau-5.3.4-3pclos2018.x86_64 ############################## [100%]

Creating symlink /var/lib/dkms/rtl88xxau/5.3.4-3pclos2018/source ->
                 /usr/src/rtl88xxau-5.3.4-3pclos2018

DKMS: add Completed.

Preparing kernel 4.19.1-pclos1 for module build:
(This is not compiling a kernel, just preparing kernel symbols)
Storing current .config to be restored when complete
Running Generic preparation routine
make clean.....
using /proc/config.gz
make oldconfig.....
make prepare.....

Building module:
cleaning build area....
'make' SKIP_STACK_VALIDATION=1 modules && 'make' install............................................
cleaning build area....
cleaning kernel tree (make clean).....

DKMS: build Completed.

rtl88xxau.ko.xz:
 - Installation
   - Installing to /lib/modules/4.19.1-pclos1/kernel/3rdparty/rtl88xxau/

depmod.....

DKMS: install Completed.
Reloading network configuration ... 
Done.
#############

**and become a version-info**
modinfo rtl88xxau
filename:       /lib/modules/4.19.1-pclos1/kernel/3rdparty/rtl88xxau/rtl88xxau.ko.xz
version:        v5.3.4_28226.20180614_COEX20171103-6c6d
author:         Realtek Semiconductor Corp.
description:    Realtek Wireless Lan Driver
license:        GPL
srcversion:     B8AEF97EE825F6093C625E7
alias:          usb:v0846p9054d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v20F4p809Bd*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v20F4p809Ad*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v2357p0106d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0BDAp8813d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v7392pA833d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v7392pA834d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v056Ep400Dd*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v056Ep400Bd*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0B05p1853d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0B05p1852d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0B05p1817d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v2001p331Ad*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0BDAp8813d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0BDApA811d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v056Ep4007d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0411p029Bd*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0846p9052d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v2019pAB32d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0411p0242d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v056Ep400Fd*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v056Ep400Ed*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0E66p0023d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v2001p3318d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v2001p3314d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v04BBp0953d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v7392pA813d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v7392pA812d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v7392pA811d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0BDAp0823d*dc*dsc*dp*icFFiscFFipFFin*
alias:          usb:v0BDAp0820d*dc*dsc*dp*icFFiscFFipFFin*
alias:          usb:v0BDApA811d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0BDAp8822d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0BDAp0821d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0BDAp0811d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0BDAp881Ad*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v2604p0012d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0BDAp8812d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v148Fp9097d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v050Dp1109d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0411p025Dd*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v20F4p805Bd*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v2357p0122d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v2357p010Fd*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v2357p010Ed*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v2357p010Dd*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v2357p0103d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v2357p0101d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v13B1p003Fd*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v2001p3316d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v2001p3315d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v2001p3313d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v2001p330Ed*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0846p9051d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v07B8p8812d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v2019pAB30d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v1740p0100d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v1058p0632d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v2001p3313d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0586p3426d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0E66p0022d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0B05p17D2d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0409p0408d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0789p016Ed*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v04BBp0952d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0DF6p0074d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v7392pA822d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v050Dp1106d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0BDAp881Cd*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0BDAp881Bd*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0BDAp881Ad*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v0BDAp8812d*dc*dsc*dp*ic*isc*ip*in*
depends:        cfg80211
retpoline:      Y
name:           rtl88xxau
vermagic:       4.19.1-pclos1 SMP mod_unload 
parm:           rtw_ips_mode:The default IPS mode (int)
parm:           rtw_lps_level:The default LPS level (int)
parm:           rtw_usb_rxagg_mode:int
parm:           rtw_dynamic_agg_enable:int
parm:           rtw_drv_log_level:set log level when insert driver module, default log level is _DRV_INFO_ = 4 (uint)
parm:           rtw_tx_bw_mode:The max tx bw for 2.4G and 5G. format is the same as rtw_bw_mode (uint)
parm:           rtw_rx_ampdu_sz_limit_1ss:RX AMPDU size limit for 1SS link of each BW, 0xFF: no limitation (array of uint)
parm:           rtw_rx_ampdu_sz_limit_2ss:RX AMPDU size limit for 2SS link of each BW, 0xFF: no limitation (array of uint)
parm:           rtw_rx_ampdu_sz_limit_3ss:RX AMPDU size limit for 3SS link of each BW, 0xFF: no limitation (array of uint)
parm:           rtw_rx_ampdu_sz_limit_4ss:RX AMPDU size limit for 4SS link of each BW, 0xFF: no limitation (array of uint)
parm:           rtw_vht_enable:int
parm:           rtw_vht_rx_mcs_map:VHT RX MCS map (uint)
parm:           rtw_rf_config:int
parm:           rtw_country_code:The default country code (in alpha2) (charp)
parm:           rtw_channel_plan:The default chplan ID when rtw_alpha2 is not specified or valid (int)
parm:           rtw_excl_chs:exclusive channel array (array of uint)
parm:           rtw_qos_opt_enable:int
parm:           ifname:The default name to allocate for first interface (charp)
parm:           if2name:The default name to allocate for second interface (charp)
parm:           rtw_pwrtrim_enable:int
parm:           rtw_initmac:charp
parm:           rtw_special_rf_path:int
parm:           rtw_chip_version:int
parm:           rtw_rfintfs:int
parm:           rtw_lbkmode:int
parm:           rtw_network_mode:int
parm:           rtw_channel:int
parm:           rtw_mp_mode:int
parm:           rtw_wmm_enable:int
parm:           rtw_vrtl_carrier_sense:int
parm:           rtw_vcs_type:int
parm:           rtw_busy_thresh:int
parm:           rtw_ht_enable:int
parm:           rtw_bw_mode:int
parm:           rtw_ampdu_enable:int
parm:           rtw_rx_stbc:int
parm:           rtw_rx_ampdu_amsdu:int
parm:           rtw_tx_ampdu_amsdu:int
parm:           rtw_beamform_cap:int
parm:           rtw_lowrate_two_xmit:int
parm:           rtw_power_mgnt:int
parm:           rtw_smart_ps:int
parm:           rtw_low_power:int
parm:           rtw_wifi_spec:int
parm:           rtw_full_ch_in_p2p_handshake:int
parm:           rtw_antdiv_cfg:int
parm:           rtw_antdiv_type:int
parm:           rtw_drv_ant_band_switch:int
parm:           rtw_single_ant_path:int
parm:           rtw_switch_usb_mode:int
parm:           rtw_enusbss:int
parm:           rtw_hwpdn_mode:int
parm:           rtw_hwpwrp_detect:int
parm:           rtw_hw_wps_pbc:int
parm:           rtw_check_hw_status:int
parm:           rtw_max_roaming_times:The max roaming times to try (uint)
parm:           rtw_mc2u_disable:int
parm:           rtw_notch_filter:0:Disable, 1:Enable, 2:Enable only for P2P (uint)
parm:           rtw_hiq_filter:0:allow all, 1:allow special, 2:deny all (uint)
parm:           rtw_adaptivity_en:0:disable, 1:enable (uint)
parm:           rtw_adaptivity_mode:0:normal, 1:carrier sense (uint)
parm:           rtw_adaptivity_dml:0:disable, 1:enable (uint)
parm:           rtw_adaptivity_dc_backoff:DC backoff for Adaptivity (uint)
parm:           rtw_adaptivity_th_l2h_ini:th_l2h_ini for Adaptivity (int)
parm:           rtw_adaptivity_th_edcca_hl_diff:th_edcca_hl_diff for Adaptivity (int)
parm:           rtw_amplifier_type_2g:BIT3:2G ext-PA, BIT4:2G ext-LNA (uint)
parm:           rtw_amplifier_type_5g:BIT6:5G ext-PA, BIT7:5G ext-LNA (uint)
parm:           rtw_RFE_type:default init value:64 (uint)
parm:           rtw_powertracking_type:default init value:64 (uint)
parm:           rtw_GLNA_type:default init value:0 (uint)
parm:           rtw_TxBBSwing_2G:default init value:0xFF (uint)
parm:           rtw_TxBBSwing_5G:default init value:0xFF (uint)
parm:           rtw_OffEfuseMask:default open Efuse Mask value:0 (uint)
parm:           rtw_FileMaskEfuse:default drv Mask Efuse value:0 (uint)
parm:           rtw_rxgain_offset_2g:default RF Gain 2G Offset value:0 (uint)
parm:           rtw_rxgain_offset_5gl:default RF Gain 5GL Offset value:0 (uint)
parm:           rtw_rxgain_offset_5gh:uint
parm:           rtw_rxgain_offset_5gm:default RF Gain 5GM Offset value:0 (uint)
parm:           rtw_pll_ref_clk_sel:force pll_ref_clk_sel, 0xF:use autoload value (uint)
parm:           rtw_tx_pwr_by_rate:0:Disable, 1:Enable, 2: Depend on efuse (int)
parm:           rtw_target_tx_pwr_2g_a:2.4G target tx power (unit:dBm) of RF path A for each rate section, should match the real calibrate power, -1: undefined (array of int)
parm:           rtw_target_tx_pwr_2g_b:2.4G target tx power (unit:dBm) of RF path B for each rate section, should match the real calibrate power, -1: undefined (array of int)
parm:           rtw_target_tx_pwr_2g_c:2.4G target tx power (unit:dBm) of RF path C for each rate section, should match the real calibrate power, -1: undefined (array of int)
parm:           rtw_target_tx_pwr_2g_d:2.4G target tx power (unit:dBm) of RF path D for each rate section, should match the real calibrate power, -1: undefined (array of int)
parm:           rtw_target_tx_pwr_5g_a:5G target tx power (unit:dBm) of RF path A for each rate section, should match the real calibrate power, -1: undefined (array of int)
parm:           rtw_target_tx_pwr_5g_b:5G target tx power (unit:dBm) of RF path B for each rate section, should match the real calibrate power, -1: undefined (array of int)
parm:           rtw_target_tx_pwr_5g_c:5G target tx power (unit:dBm) of RF path C for each rate section, should match the real calibrate power, -1: undefined (array of int)
parm:           rtw_target_tx_pwr_5g_d:5G target tx power (unit:dBm) of RF path D for each rate section, should match the real calibrate power, -1: undefined (array of int)
parm:           rtw_phy_file_path:The path of phy parameter (charp)
parm:           rtw_load_phy_file:PHY File Bit Map (int)
parm:           rtw_decrypt_phy_file:Enable Decrypt PHY File (int)
parm:           rtw_en_napi:int
parm:           rtw_en_gro:int
parm:           rtw_iqk_fw_offload:int
parm:           rtw_ch_switch_offload:int
################
all without connected a wifi-usb-dongle, hope this help you all doing step's forward 
i'm unsafe is all right so
cheers

**Comment by Yes21** [comment]
> So do I only need to add `CONFIG_PLATFORM_ARM_RPI=y` in the Makefile, to be able to compile on RPI ?

It seems that it's not enough because I don't succeed in compiling the driver on RPI (Raspbian 4.14.71)
Does any one have already compiled 5.3.4 on a RPI ?

**Comment by kimocoder** [comment]
Merged some changes. Long time no see!

* Added support for RPI and Odroid C2
* Update kernel v4.19 support
* Added kernel v4.20 support and turned a compiler warning off

I also removed some firmware load by removing some unused functions and did a code cleanup.

**Comment by Yes21** [comment]
@kimocoder 

> Added support for RPI 

Many thanks :-)
I will test it soon ...

**Comment by fastkms** [comment]
Hi, my name is min. 
I'm sorry interfere this section. But I need help, and I think you are best engineer. 
I develop wifi sniffer with RPI + RTL8812 (for indoor location tracking)
RTL8812 driver loaded MONITOR mode(5.1.5 version).
But RSSI value is non-linear.
I think RX AGC function affect RSSI value.(is right? or RSSI measureed before AGC?)
 
I want to turn off RX AGC function. but I can't.
'phydm_rxhp.c' file include ODM_SetBBReg(pDM_Odm, 0xC70, BIT0, 0); <--turn off Rx AGC
But 'phydm_rxhp.c' file is not compiled, because of that file is not found in makefile.
How can I turn OFF RX AGC function.
Please help me.

**Comment by fariouche** [comment]
@fastkms , please open a specific issue. This one is only to track the work in progress. (by the way, sorry, no idea about your issue)
Thanks

**Comment by fariouche** [comment]
Thanks to the ameter, I can check the txpower... so far, no success, even with older driver (5.2.20)...
I'm using iw dev wlan0 set txpower fixed 2000 to set 20dbm or 200 to reduce power, and I see no effect :(

**Comment by iyanmv** [comment]
Hi all! First of all thanks for all your work with this driver. I was reading this issue to try to understand the differences between the branches v5.2.20 and the v5.3.4.

If I understood correctly, these two branches have different basis (due to different origins of the code) and v5.3.4 looks "more promising", but just by checking last commits, branch v5.2.20 seems more active. Am I right?

Would it be possible to add a small comparative table between these branches in the README (known issues, different features, etc.)?

**Comment by kimocoder** [comment]
Well, yes v5.3.4 is a more stable base, but unfortunately there was issues with the penetration testing abilities on it so we left it for some time and updated the v5.2.20(.2) instead.

Now we're looking into the v5.3.9 base, which is even nicer.. but it aquire lots of work to re-write functions and make HAL, phydm and halrf fit into the base.

**Comment by iyanmv** [comment]
Ok, I understand, thanks! So for injection and other penetration testing better to stay in v5.2.20(.2) for the moment. I'll keep an eye on future updates and that new branch :wink:

**Comment by kimocoder** [comment]
Yes sir, I'll take a look at injection issues of v5.3.4 soon anyhow.. see if I'll find it
